server:
  port: 8080

eureka:
    client:
      register-with-eureka: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clients
          uri: http://localhost:8081
          predicates:
            - Path=/api/client/**
        - id: doctors
          uri: http://localhost:8082
          predicates:
            - Path=/api/doctor/**
        - id: reserves
          uri: http://localhost:8083
          predicates:
            - Path=/api/appointment/**